"""add users and prompt ownership

Revision ID: 029c3a99626c
Revises: 1adcf3e7ccc5
Create Date: 2026-08-06 14:19:47.381567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029c3a99626c'
down_revision: Union[str, Sequence[str], None] = '1adcf3e7ccc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
