"""add users and prompt ownership

Revision ID: a2f344ddb14b
Revises: a5bef82d9e15
Create Date: 2026-08-06 14:18:00.318829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f344ddb14b'
down_revision: Union[str, Sequence[str], None] = 'a5bef82d9e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('prompt_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prompt_history_user_id'), 'prompt_history', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_prompt_history_user_id_users'), 'prompt_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_prompt_history_user_id_users'), 'prompt_history', type_='foreignkey')
    op.drop_index(op.f('ix_prompt_history_user_id'), table_name='prompt_history')
    op.drop_column('prompt_history', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
