"""create prompt history table

Revision ID: c085f4fe6ef0
Revises: 
Create Date: 2026-08-05 17:46:39.079890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c085f4fe6ef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weak_prompt', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improved_prompt', sa.Text(), nullable=False),
    sa.Column('transformation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_history'))
    )
    op.create_index(op.f('ix_prompt_history_category'), 'prompt_history', ['category'], unique=False)
    op.create_index('ix_prompt_history_category_created_at', 'prompt_history', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_prompt_history_created_at'), 'prompt_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_history_is_favorite'), 'prompt_history', ['is_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_history_is_favorite'), table_name='prompt_history')
    op.drop_index(op.f('ix_prompt_history_created_at'), table_name='prompt_history')
    op.drop_index('ix_prompt_history_category_created_at', table_name='prompt_history')
    op.drop_index(op.f('ix_prompt_history_category'), table_name='prompt_history')
    op.drop_table('prompt_history')
    # ### end Alembic commands ###
